create table "public"."company" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text
);


create table "public"."profile" (
    "id" integer generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "nickname" text
);


alter table "public"."employees" add column "company_id" bigint;

alter table "public"."employees" alter column "id" set generated by default;

CREATE UNIQUE INDEX company_pkey ON public.company USING btree (id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (id);

alter table "public"."company" add constraint "company_pkey" PRIMARY KEY using index "company_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."employees" add constraint "employees_company_id_fkey" FOREIGN KEY (company_id) REFERENCES company(id) not valid;

alter table "public"."employees" validate constraint "employees_company_id_fkey";

alter table "public"."profile" add constraint "profile_id_fkey" FOREIGN KEY (id) REFERENCES employees(id) not valid;

alter table "public"."profile" validate constraint "profile_id_fkey";


