-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public.employees FROM authenticated;
REVOKE ALL ON TABLE public.employees FROM postgres;
REVOKE ALL ON TABLE public.employees FROM service_role;
GRANT ALL ON TABLE public.employees TO authenticated;

GRANT ALL ON TABLE public.employees TO postgres;

GRANT ALL ON TABLE public.employees TO service_role;

ALTER TABLE IF EXISTS public.employees
    ADD COLUMN new text COLLATE pg_catalog."default" DEFAULT 'stuff'::text;
